Repository kakao-tech-campus-2nd-step3/Team29_Android, pull requests merged in 2024-10, with the labels that each got.

#51 Feat: 주석 관련 레포지토리 추상체&구현체 구현 & Refactor: Repository Module 분리
  core/data/src/main/java/com/iguana/data/di/DataModule.kt
  core/data/src/main/java/com/iguana/data/di/RepositoryModule.kt
  core/data/src/main/java/com/iguana/data/mapper/AnnotationMapper.kt
  core/data/src/main/java/com/iguana/data/repository/AnnotationRepositoryImpl.kt
  core/domain/src/main/java/com/iguana/domain/model/.gitkeep
  core/domain/src/main/java/com/iguana/domain/model/Annotation.kt
  core/domain/src/main/java/com/iguana/domain/repository/AnnotationRepository.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/PDFBoxActivity.kt
Labels: 🌟 Feat, ♻️ Refactor

#59 Feat: 주석 외부라이브러리 사용 시
  .idea/deploymentTargetDropDown.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  feature/notetaking/build.gradle.kts
  feature/notetaking/src/main/java/com/iguana/notetaking/NotetakingActivity.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/PdfPageFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/PdfViewerFragment.kt
  feature/notetaking/src/main/res/drawable/textbox_background.xml
  feature/notetaking/src/main/res/layout/fragment_pdf_page.xml
  feature/notetaking/src/main/res/layout/text_toolbar.xml
Labels: 🌟 Feat, 🐌 Later

#61 [Feat] 필기 화면 페이지 확대/축소, 이동 이벤트 처리
  .idea/misc.xml
  build.gradle.kts
  feature/notetaking/build.gradle.kts
  feature/notetaking/src/main/java/com/iguana/notetaking/AiFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/AiViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/NotetakingActivity.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/PdfPageFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/PdfViewerFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/PdfViewerViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/RecordFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/RecordViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/SideBarFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/SidebarAdapter.kt
  feature/notetaking/src/main/res/drawable/page_box_background.xml
  feature/notetaking/src/main/res/layout/fragment_ai.xml
  feature/notetaking/src/main/res/layout/fragment_pdf_page.xml
  feature/notetaking/src/main/res/layout/fragment_record.xml
  settings.gradle.kts
Labels: 🌟 Feat

#65 [Feat] Record 관련 모델, data layer 구현
  core/data/src/main/java/com/iguana/data/di/DataModule.kt
  core/data/src/main/java/com/iguana/data/local/files/FileHelperImpl.kt
  core/data/src/main/java/com/iguana/data/local/files/RecordingFileStorage.kt
  core/data/src/main/java/com/iguana/data/mapper/RecordMapper.kt
  core/data/src/main/java/com/iguana/data/remote/api/RecordApi.kt
  core/data/src/main/java/com/iguana/data/remote/model/RecordDto.kt
  core/data/src/main/java/com/iguana/data/repository/RecordRepositoryImpl.kt
  core/domain/src/main/java/com/iguana/domain/model/record/PageTurnEvent.kt
  core/domain/src/main/java/com/iguana/domain/model/record/RecordingFile.kt
  core/domain/src/main/java/com/iguana/domain/model/record/RecordingSession.kt
  core/domain/src/main/java/com/iguana/domain/model/record/RecordingState.kt
  core/domain/src/main/java/com/iguana/domain/repository/RecordRepository.kt
  core/domain/src/main/java/com/iguana/domain/utils/AppError.kt
Labels: 🌟 Feat

#67 [Refactor] DataModule, AppDatabase 피드백 반영
  core/data/src/main/java/com/iguana/data/di/DataModule.kt
  core/data/src/main/java/com/iguana/data/local/db/AppDatabase.kt
Labels: ♻️ Refactor

#75 [Refactor] : Weekly6 피드백 반영
  core/data/src/main/java/com/iguana/data/local/dao/RecentFileDao.kt
  core/data/src/main/java/com/iguana/data/repository/DocumentsRepositoyImpl.kt
  core/data/src/main/java/com/iguana/data/utils/Logger.kt
  core/domain/src/main/java/com/iguana/domain/repository/DocumentsRepository.kt
  core/domain/src/main/java/com/iguana/domain/usecase/GetAllDocumentsUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/GetSubItemsUseCase.kt
  feature/documents/src/main/java/com/iguana/documents/DocumentsFragment.kt
  feature/documents/src/main/java/com/iguana/documents/DocumentsViewModel.kt
  feature/documents/src/main/res/layout-sw600dp/fragment_documents.xml
  feature/documents/src/main/res/layout/fragment_documents.xml
  feature/settings/src/main/res/layout-sw600dp/fragment_settings.xml
Labels: ♻️ Refactor

#76 [Fix] PhotoEditView Library 제거 -> mergeDebugResources 에러 해결
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/styles.xml
  build-logic/src/main/kotlin/com/iguana/notai/KotlinAndroid.kt
  core/data/build.gradle.kts
  core/data/src/main/java/com/iguana/data/repository/RecordRepositoryImpl.kt
  core/designsystem/src/main/res/values/styles.xml
  core/ui/src/main/res/values/styles.xml
  feature/dashBoard/src/main/res/values/styles.xml
  feature/login/src/main/java/com/iguana/login/LoginActivity.kt
  feature/notetaking/build.gradle.kts
  feature/notetaking/src/main/java/com/iguana/notetaking/PdfPageFragment.kt
  feature/notetaking/src/main/res/layout/fragment_pdf_page.xml
  feature/notetaking/src/main/res/values/styles.xml
  feature/settings/build.gradle.kts
  feature/userInfo/build.gradle.kts
Labels: 🕸️ Bug

#78 [Feat] AI 기능 구현 및 더미 데이터 삽입
  core/data/src/main/java/com/iguana/data/di/NetworkModule.kt
  core/data/src/main/java/com/iguana/data/di/RepositoryModule.kt
  core/data/src/main/java/com/iguana/data/mapper/SummarizeMapper.kt
  core/data/src/main/java/com/iguana/data/remote/api/SummarizeApi.kt
  core/data/src/main/java/com/iguana/data/remote/model/SummarizeDto.kt
  core/data/src/main/java/com/iguana/data/repository/AIRepositoryImpl.kt
  core/designsystem/src/main/res/values-sw600dp/dimens.xml
  core/designsystem/src/main/res/values/dimens.xml
  core/designsystem/src/main/res/values/styles.xml
  core/domain/src/main/java/com/iguana/domain/model/ai/AIResult.kt
  core/domain/src/main/java/com/iguana/domain/model/ai/AIStatusResult.kt
  core/domain/src/main/java/com/iguana/domain/repository/AIRepository.kt
  core/domain/src/main/java/com/iguana/domain/usecase/GetAIResultByPageUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/GetAIStatusByPageUseCase.kt
  feature/dashBoard/src/main/java/com/iguana/dashBoard/RecentFilesViewModel.kt
  feature/login/src/main/java/com/iguana/login/LoginActivity.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/NotetakingActivity.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/ai/AiFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/ai/AiViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/recording/RecordFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/recording/RecordViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/sidebar/SideBarFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/sidebar/SidebarAdapter.kt
  feature/notetaking/src/main/res/layout-sw600dp/fragment_ai.xml
  feature/notetaking/src/main/res/layout/fragment_ai.xml
  feature/notetaking/src/main/res/values/strings.xml
Labels: 🌟 Feat

#82 [Fix] Bearer 관련 에러 수정
  core/data/src/main/java/com/iguana/data/di/AuthInterceptor.kt
  core/data/src/main/java/com/iguana/data/di/NetworkModule.kt
  core/data/src/main/java/com/iguana/data/remote/api/DocumentApi.kt
  core/data/src/main/java/com/iguana/data/repository/DocumentsRepositoyImpl.kt
  core/domain/src/main/java/com/iguana/domain/repository/DocumentsRepository.kt
  core/domain/src/main/java/com/iguana/domain/usecase/SaveFileInRemoteUsecase.kt
  feature/dashBoard/src/main/java/com/iguana/dashBoard/RecentFilesViewModel.kt
  feature/login/src/main/java/com/iguana/login/LoginActivity.kt
Labels: 🕸️ Bug

#83 [Refactor] Weekly6, 멘토링 피드백 반영
  core/data/src/main/java/com/iguana/data/local/db/AppDatabase.kt
  core/data/src/main/java/com/iguana/data/local/files/RecordingFileStorage.kt
  core/data/src/main/java/com/iguana/data/repository/RecordRepositoryImpl.kt
  core/domain/src/main/java/com/iguana/domain/model/ai/AIResult.kt
  core/domain/src/main/java/com/iguana/domain/repository/RecordRepository.kt
  core/domain/src/main/java/com/iguana/domain/utils/AppError.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/NotetakingActivity.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/NotetakingViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/ai/AiFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/ai/AiViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/recording/RecordFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/recording/RecordViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/sidebar/SideBarFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/sidebar/SideBarViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/sidebar/SidebarAdapter.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/util/ViewExtensions.kt
Labels: 🕸️ Bug, ♻️ Refactor

#88 [Feat] 녹음 기능 구현
  .idea/deploymentTargetDropDown.xml
  core/data/build.gradle.kts
  core/data/src/main/java/com/iguana/data/di/DataModule.kt
  core/data/src/main/java/com/iguana/data/di/NetworkModule.kt
  core/data/src/main/java/com/iguana/data/di/RepositoryModule.kt
  core/data/src/main/java/com/iguana/data/local/files/RecordingFileStorage.kt
  core/data/src/main/java/com/iguana/data/mapper/RecordMapper.kt
  core/data/src/main/java/com/iguana/data/remote/model/RecordDto.kt
  core/data/src/main/java/com/iguana/data/repository/RecordRepositoryImpl.kt
  core/domain/src/main/java/com/iguana/domain/model/record/PageTurnEvent.kt
  core/domain/src/main/java/com/iguana/domain/repository/RecordRepository.kt
  core/domain/src/main/java/com/iguana/domain/usecase/DeletePageTurnEventsUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/DeleteRecordingUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/SavePageTurnEventUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/UploadPageTurnEventsUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/UploadRecordingUseCase.kt
  feature/dashBoard/src/main/java/com/iguana/dashBoard/RecentFilesViewModel.kt
  feature/notetaking/src/main/AndroidManifest.xml
  feature/notetaking/src/main/java/com/iguana/notetaking/NotetakingActivity.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/NotetakingViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/recording/RecordFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/recording/RecordViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/recording/RecordingService.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/sidebar/SideBarFragment.kt
  feature/notetaking/src/main/res/layout-sw600dp/titlebar.xml
  feature/notetaking/src/main/res/layout/activity_notetaking.xml
  feature/notetaking/src/main/res/layout/fragment_record.xml
  feature/notetaking/src/main/res/layout/titlebar.xml
  feature/notetaking/src/main/res/values/strings.xml
Labels: 🌟 Feat

#94 [Design] 즐겨찾기 화면 제작
  core/ui/build.gradle.kts
  core/ui/src/main/java/com/iguana/ui/BaseActivity.kt
  core/ui/src/main/java/com/iguana/ui/SideTabLayoutFragment.kt
  feature/favorites/build.gradle.kts
  feature/favorites/src/main/java/com/iguana/favorites/FavoritesFragment.kt
  feature/favorites/src/main/res/layout-sw600dp/fragment_favorites.xml
  feature/favorites/src/main/res/layout/fragment_favorites.xml
Labels: 🎨 Design
