Repository kakao-tech-campus-2nd-step3/Team29_Android, pull requests merged in 2024-11, with the labels that each got.

#95 [Refactor] Weekly8 피드백 반영
  core/data/src/main/java/com/iguana/data/di/AuthInterceptor.kt
  core/data/src/main/java/com/iguana/data/di/DataModule.kt
  core/data/src/main/java/com/iguana/data/di/NetworkModule.kt
  core/data/src/main/java/com/iguana/data/local/db/AppDatabase.kt
  core/data/src/main/java/com/iguana/data/local/entity/PageTurnEventDao.kt
  core/data/src/main/java/com/iguana/data/local/entity/PageTurnEventEntity.kt
  core/data/src/main/java/com/iguana/data/mapper/RecordMapper.kt
  core/data/src/main/java/com/iguana/data/remote/api/SummarizeApi.kt
  core/data/src/main/java/com/iguana/data/repository/AIRepositoryImpl.kt
  core/data/src/main/java/com/iguana/data/repository/RecordRepositoryImpl.kt
  core/domain/src/main/java/com/iguana/domain/model/ai/AIResult.kt
  core/domain/src/main/java/com/iguana/domain/repository/AIRepository.kt
  core/domain/src/main/java/com/iguana/domain/repository/RecordRepository.kt
  core/domain/src/main/java/com/iguana/domain/usecase/UploadPageTurnEventsUseCase.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/NotetakingActivity.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/NotetakingViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/recording/RecordFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/recording/RecordViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/sidebar/SideBarFragment.kt
  feature/notetaking/src/main/res/layout-sw600dp/activity_notetaking.xml
  feature/notetaking/src/main/res/layout/activity_notetaking.xml
Labels: ♻️ Refactor

#98 [Feat] 주석 기능(화면에 띄우는 정도로만) 구현
  core/data/src/main/java/com/iguana/data/di/DataModule.kt
  core/data/src/main/java/com/iguana/data/local/dao/AnnotationDao.kt
  core/data/src/main/java/com/iguana/data/local/dao/PageTurnEventDao.kt
  core/data/src/main/java/com/iguana/data/local/db/AppDatabase.kt
  core/data/src/main/java/com/iguana/data/local/entity/AnnotationEntity.kt
  core/data/src/main/java/com/iguana/data/mapper/AnnotationMapper.kt
  core/data/src/main/java/com/iguana/data/mapper/RecordMapper.kt
  core/data/src/main/java/com/iguana/data/repository/AnnotationRepositoryImpl.kt
  core/data/src/main/java/com/iguana/data/repository/RecordRepositoryImpl.kt
  core/designsystem/src/main/res/drawable/ic_at_array.xml
  core/designsystem/src/main/res/drawable/ic_at_back.xml
  core/designsystem/src/main/res/drawable/ic_at_bold.xml
  core/designsystem/src/main/res/drawable/ic_at_chevron_down.xml
  core/designsystem/src/main/res/drawable/ic_at_color_black.xml
  core/designsystem/src/main/res/drawable/ic_at_italic.xml
  core/designsystem/src/main/res/drawable/ic_at_next.xml
  core/designsystem/src/main/res/drawable/ic_at_nums_array.xml
  core/designsystem/src/main/res/drawable/ic_at_strike_through.xml
  core/designsystem/src/main/res/drawable/ic_at_text_align_center.xml
  core/designsystem/src/main/res/drawable/ic_at_text_align_justify.xml
  core/designsystem/src/main/res/drawable/ic_at_text_align_left.xml
  core/designsystem/src/main/res/drawable/ic_at_text_align_right.xml
  core/designsystem/src/main/res/drawable/ic_at_text_delete.xml
  core/designsystem/src/main/res/drawable/ic_at_underscore.xml
  core/domain/src/main/java/com/iguana/domain/model/Annotation.kt
  core/domain/src/main/java/com/iguana/domain/repository/AnnotationRepository.kt
  core/domain/src/main/java/com/iguana/domain/usecase/ClearAnnotationsUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/LoadAnnotationsUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/SaveAnnotationUseCase.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/NotetakingActivity.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/NotetakingViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/PdfPageFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/pdf/PdfEditor.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/pdf/PdfPageAdapter.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/pdf/PdfPageFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/pdf/PdfPageViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/pdf/PdfViewerFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/pdf/PdfViewerViewModel.kt
  feature/notetaking/src/main/res/layout-sw600dp/activity_notetaking.xml
  feature/notetaking/src/main/res/layout/activity_notetaking.xml
  feature/notetaking/src/main/res/layout/text_align_dropdown.xml
  feature/notetaking/src/main/res/layout/text_color_dropdown.xml
  feature/notetaking/src/main/res/layout/text_edit_bar.xml
  feature/notetaking/src/main/res/layout/text_format_icons.xml
  feature/notetaking/src/main/res/layout/text_list_icons.xml
  feature/notetaking/src/main/res/layout/text_size_dropdown.xml
  feature/notetaking/src/main/res/layout/toolbar.xml
Labels: 🌟 Feat

#102 [Feat] Document 서버에 업로드
  core/data/src/main/AndroidManifest.xml
  core/data/src/main/java/com/iguana/data/di/NetworkModule.kt
  core/data/src/main/java/com/iguana/data/mapper/DocumentsMapper.kt
  core/data/src/main/java/com/iguana/data/remote/model/DocumentsDto.kt
  feature/dashBoard/src/main/java/com/iguana/dashBoard/RecentFilesViewModel.kt
  feature/notetaking/src/main/AndroidManifest.xml
  feature/notetaking/src/main/java/com/iguana/notetaking/pdf/PdfPageFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/pdf/PdfViewerViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/util/PdfRendererHelper.kt
  feature/notetaking/src/main/res/xml/network_security_config.xml
Labels: 🌟 Feat

#104 [Refactor] Weekly9 코드리뷰 사항 반영했습니다 (사이드바 버그 해결)
  core/data/build.gradle.kts
  core/data/src/main/java/com/iguana/data/di/DataModule.kt
  core/data/src/main/java/com/iguana/data/di/NetworkModule.kt
  core/data/src/main/java/com/iguana/data/local/files/RecordingFileStorage.kt
  core/data/src/main/java/com/iguana/data/mapper/RecordMapper.kt
  core/data/src/main/java/com/iguana/data/remote/api/RecordApi.kt
  core/data/src/main/java/com/iguana/data/repository/RecordRepositoryImpl.kt
  core/domain/src/main/java/com/iguana/domain/model/ai/AIResult.kt
  core/domain/src/main/java/com/iguana/domain/utils/AppError.kt
  feature/dashBoard/src/main/java/com/iguana/dashBoard/RecentFilesViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/NotetakingViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/ai/AiFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/ai/AiViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/pdf/AnnotationEditor.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/pdf/PdfPageFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/recording/RecordFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/recording/RecordViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/recording/RecordingActions.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/recording/RecordingService.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/sidebar/SideBarFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/sidebar/SidebarAdapter.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/util/HtmlFormatter.kt
  feature/notetaking/src/main/res/layout-sw600dp/fragment_ai.xml
  feature/notetaking/src/main/res/layout/fragment_ai.xml
  feature/notetaking/src/main/res/layout/fragment_pdf_page.xml
  feature/notetaking/src/main/res/layout/fragment_record.xml
  feature/notetaking/src/main/res/values/strings.xml
Labels: 🕸️ Bug, 🌟 Feat, ♻️ Refactor

#111 [Feat & Design] 주석 핵심 기능 구현 & 앱 테마 설정 및 아이콘 추가
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/notai_logo.xml
  app/src/main/res/drawable/notai_round_logo.xml
  core/data/src/main/java/com/iguana/data/local/dao/AnnotationDao.kt
  core/data/src/main/java/com/iguana/data/local/entity/AnnotationEntity.kt
  core/data/src/main/java/com/iguana/data/mapper/AnnotationMapper.kt
  core/data/src/main/java/com/iguana/data/remote/api/AnnotationApi.kt
  core/data/src/main/java/com/iguana/data/remote/model/AnnotationDto.kt
  core/data/src/main/java/com/iguana/data/repository/AnnotationRepositoryImpl.kt
  core/designsystem/src/main/res/values-sw320dp/dimens.xml
  core/designsystem/src/main/res/values-sw600dp/dimens.xml
  core/designsystem/src/main/res/values/dimens.xml
  core/designsystem/src/main/res/values/styles.xml
  core/domain/src/main/java/com/iguana/domain/model/Annotation.kt
  core/domain/src/main/java/com/iguana/domain/repository/AnnotationRepository.kt
  core/domain/src/main/java/com/iguana/domain/repository/GetAnnotationsByPageUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/CacheAnnotationsToLocalUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/DeleteAnnotationUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/SaveAnnotationUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/UpdateAnnotationUseCase.kt
  core/ui/src/main/java/com/iguana/ui/BaseActivity.kt
  core/ui/src/main/java/com/iguana/ui/StatusBarManager.kt
  core/ui/src/main/res/drawable/right_border.xml
  core/ui/src/main/res/layout-sw600dp/activity_base.xml
  core/ui/src/main/res/layout-sw600dp/fragment_side_tab_layout.xml
  core/ui/src/main/res/layout/fragment_side_tab_layout.xml
  feature/dashBoard/src/main/res/layout-sw600dp/activity_dash_borad_fragment.xml
  feature/dashBoard/src/main/res/layout-sw600dp/fragment_dash_board.xml
  feature/documents/src/main/res/layout-sw600dp/fragment_documents.xml
  feature/documents/src/main/res/layout/fragment_documents.xml
  feature/favorites/src/main/res/layout-sw600dp/fragment_favorites.xml
  feature/favorites/src/main/res/layout/fragment_favorites.xml
  feature/login/src/main/res/layout-sw600dp/activity_login.xml
  feature/login/src/main/res/layout/activity_login.xml
  feature/notetaking/build.gradle.kts
  feature/notetaking/src/main/java/com/iguana/notetaking/NotetakingActivity.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/pdf/AnnotationEditor.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/pdf/PdfPageFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/pdf/PdfPageViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/pdf/PdfViewerFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/pdf/PdfViewerViewModel.kt
  feature/settings/src/main/res/layout-sw600dp/fragment_settings.xml
  feature/settings/src/main/res/layout/fragment_settings.xml
  feature/userInfo/src/main/res/layout-sw600dp/fragment_userinfo.xml
  feature/userInfo/src/main/res/layout/fragment_userinfo.xml
Labels: 🌟 Feat, 🎨 Design

#120 [Refactor] AI 완료 대기 시 UI 변경
  core/designsystem/src/main/res/drawable/ic_refresh.xml
  core/designsystem/src/main/res/drawable/ic_refresh_white.xml
  core/designsystem/src/main/res/values-sw320dp/dimens.xml
  core/designsystem/src/main/res/values-sw600dp/dimens.xml
  core/designsystem/src/main/res/values/dimens.xml
  core/domain/src/main/java/com/iguana/domain/model/ai/AIStatusResult.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/NotetakingActivity.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/NotetakingViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/ai/AiFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/ai/AiViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/sidebar/SideBarFragment.kt
  feature/notetaking/src/main/res/layout-sw600dp/activity_notetaking.xml
  feature/notetaking/src/main/res/layout-sw600dp/fragment_ai.xml
  feature/notetaking/src/main/res/layout/fragment_ai.xml
  feature/notetaking/src/main/res/values/strings.xml
  feature/userInfo/src/main/res/layout-sw600dp/fragment_userinfo.xml
Labels: ♻️ Refactor, 🎨 Design

#126 [Fix] Document -> Notetaking 안넘어가는 버그 해결 및 Response 타입들 제거
  app/.gitignore
  app/build.gradle.kts
  core/data/src/main/java/com/iguana/data/di/NetworkModule.kt
  core/data/src/main/java/com/iguana/data/mapper/DocumentsMapper.kt
  core/data/src/main/java/com/iguana/data/mapper/FolderOrDocumentResponseDtoAdapter.kt
  core/data/src/main/java/com/iguana/data/remote/api/DocumentApi.kt
  core/data/src/main/java/com/iguana/data/remote/model/DocumentsDto.kt
  core/data/src/main/java/com/iguana/data/repository/DocumentsRepositoyImpl.kt
  core/data/src/main/java/com/iguana/data/repository/RecordRepositoryImpl.kt
  core/data/src/main/java/com/iguana/data/utils/DocumentsParser.kt
  core/domain/src/main/java/com/iguana/domain/model/Document.kt
  core/domain/src/main/java/com/iguana/domain/repository/DocumentsRepository.kt
  core/domain/src/main/java/com/iguana/domain/usecase/CreateFolderUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/DeleteFileUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/DeleteFolderUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/GetAllDocumentsUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/GetFolderContentsUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/SaveFileInRemoteUsecase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/UpdateDocumentNameUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/UpdateFolderNameUseCase.kt
  feature/dashBoard/src/main/java/com/iguana/dashBoard/RecentFilesViewModel.kt
  feature/dashBoard/src/main/res/layout-sw600dp/fragment_ai_history.xml
  feature/documents/build.gradle.kts
  feature/documents/src/main/java/com/iguana/documents/DocumentsAdapter.kt
  feature/documents/src/main/java/com/iguana/documents/DocumentsFragment.kt
  feature/documents/src/main/java/com/iguana/documents/DocumentsViewModel.kt
  feature/documents/src/main/res/drawable/default_card_background.xml
  feature/documents/src/main/res/drawable/documents_pdf.xml
  feature/documents/src/main/res/layout-sw600dp/fragment_documents.xml
  feature/documents/src/main/res/layout/item_documents_pdf.xml
Labels: 🕸️ Bug, ♻️ Refactor

#135 [Refactor] 로그아웃 버그 수정
  .idea/gradle.xml
  core/data/src/main/java/com/iguana/data/local/db/SharedPreferencesHelperImpl.kt
  core/data/src/main/java/com/iguana/data/repository/LoginRepositorylmpl.kt
  core/data/src/main/java/com/iguana/data/repository/SharedPreferencesHelperImpl.kt
  core/domain/src/main/java/com/iguana/domain/repository/LoginRepository.kt
  core/domain/src/main/java/com/iguana/domain/repository/SharedPreferencesHelper.kt
  core/navigation/build.gradle.kts
  core/navigation/consumer-rules.pro
  core/navigation/proguard-rules.pro
  core/navigation/src/androidTest/java/com/iguana/navigation/ExampleInstrumentedTest.kt
  core/navigation/src/main/AndroidManifest.xml
  core/navigation/src/main/java/com/iguana/navigation/LoginNavigator.kt
  core/navigation/src/test/java/com/iguana/navigation/ExampleUnitTest.kt
  core/ui/build.gradle.kts
  core/ui/src/main/java/com/iguana/ui/BaseActivity.kt
  feature/userInfo/build.gradle.kts
  feature/userInfo/src/main/java/com/iguana/userinfo/UserInfoFragment.kt
  feature/userInfo/src/main/java/com/iguana/userinfo/UserInfoViewModel.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 🕸️ Bug, ♻️ Refactor

#138 [Fix] Document 에서 파일 접근 후 최근 파일 DB 에 저장하는 코드 누락 해결
  core/data/src/main/java/com/iguana/data/mapper/SttMapper.kt
  core/data/src/main/java/com/iguana/data/remote/model/DocumentsDto.kt
  core/data/src/main/java/com/iguana/data/repository/DocumentsRepositoyImpl.kt
  core/domain/src/main/java/com/iguana/domain/model/Document.kt
  core/domain/src/main/java/com/iguana/domain/usecase/GetSTTResultByPageUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/GetSTTStatusByPageUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/UpdateFolderNameUseCase.kt
  feature/documents/src/main/java/com/iguana/documents/DocumentsFragment.kt
  feature/documents/src/main/java/com/iguana/documents/DocumentsViewModel.kt
  feature/documents/src/main/res/layout-sw600dp/fragment_documents.xml
  feature/notetaking/src/main/java/com/iguana/notetaking/recording/RecordFragment.kt
Labels: 🕸️ Bug

#140 [Fix] Annotation 인터랙션 관련 세부 수정
  app/src/main/AndroidManifest.xml
  core/data/src/main/java/com/iguana/data/repository/AnnotationRepositoryImpl.kt
  core/ui/src/main/AndroidManifest.xml
  feature/dashBoard/src/main/AndroidManifest.xml
  feature/documents/src/main/AndroidManifest.xml
  feature/documents/src/main/res/layout-sw600dp/fragment_documents.xml
  feature/login/src/main/AndroidManifest.xml
  feature/notetaking/src/main/AndroidManifest.xml
  feature/notetaking/src/main/java/com/iguana/notetaking/NotetakingActivity.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/pdf/AnnotationEditor.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/pdf/PdfPageFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/pdf/PdfPageViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/pdf/PdfViewerFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/recording/RecordFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/recording/RecordViewModel.kt
  feature/notetaking/src/main/res/layout/text_format_icons.xml
  feature/notetaking/src/main/res/values/strings.xml
Labels: ✨ Performance

#145 [Fix] 주석 버그 해결
  .idea/gradle.xml
  app/build.gradle.kts
  core/data/src/main/java/com/iguana/data/local/dao/RecentFileDao.kt
  core/data/src/main/java/com/iguana/data/local/entity/RecentFileEntity.kt
  core/data/src/main/java/com/iguana/data/repository/RecentFileRepositoryImpl.kt
  core/designsystem/src/main/java/com/iguana/designsystem/sample/LoadingDialog.kt
  core/designsystem/src/main/res/layout/dialog_loading.xml
  core/domain/src/main/java/com/iguana/domain/model/RecentFile.kt
  core/domain/src/main/java/com/iguana/domain/repository/RecentFileRepository.kt
  core/domain/src/main/java/com/iguana/domain/usecase/DeleteRecentFileUseCase.kt
  core/domain/src/main/java/com/iguana/domain/usecase/UpdateRecentFileUseCase.kt
  feature/dashBoard/src/main/java/com/iguana/dashBoard/RecentFilesAdapter.kt
  feature/dashBoard/src/main/java/com/iguana/dashBoard/RecentFilesViewModel.kt
  feature/dashBoard/src/main/res/layout/item_recent_files.xml
  feature/documents/src/main/java/com/iguana/documents/DocumentsFragment.kt
  feature/documents/src/main/java/com/iguana/documents/DocumentsViewModel.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/ai/AiFragment.kt
  feature/notetaking/src/main/java/com/iguana/notetaking/pdf/AnnotationEditor.kt
Labels: 🕸️ Bug
